2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: Card clicked: 9♣
2025-05-06 10:03 - DEBUG: Making card active: 9♣
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: <card.Card object at 0x79131fe8a9d0>
2025-05-06 10:03 - DEBUG: Deactivating the card 9♣
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:03 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: 8♠
2025-05-06 10:05 - DEBUG: Activating the card: 8♠
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a56a30>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a56a30>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a56a30>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a56a30>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a56a30>
2025-05-06 10:05 - DEBUG: Deactivating the card 8♠
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: 2♦
2025-05-06 10:05 - DEBUG: Activating the card: 2♦
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a61550>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a61550>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a61550>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a61550>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a61550>
2025-05-06 10:05 - DEBUG: Deactivating the card 2♦
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: 2♥
2025-05-06 10:05 - DEBUG: Activating the card: 2♥
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a942d0>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a942d0>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a942d0>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a942d0>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a942d0>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a942d0>
2025-05-06 10:05 - DEBUG: Deactivating the card 2♥
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: 3♥
2025-05-06 10:05 - DEBUG: Activating the card: 3♥
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:05 - DEBUG: Deactivating the card 3♥
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: 5♥
2025-05-06 10:05 - DEBUG: Activating the card: 5♥
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: Deactivating the card 5♥
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: 2♠
2025-05-06 10:05 - DEBUG: Activating the card: 2♠
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: Deactivating the card 2♠
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: A♣
2025-05-06 10:05 - DEBUG: Activating the card: A♣
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779a60f50>
2025-05-06 10:05 - DEBUG: Deactivating the card A♣
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: 5♥
2025-05-06 10:05 - DEBUG: Activating the card: 5♥
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: Deactivating the card 5♥
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: 5♥
2025-05-06 10:05 - DEBUG: Activating the card: 5♥
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: Deactivating the card 5♥
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: 5♥
2025-05-06 10:05 - DEBUG: Activating the card: 5♥
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779be6190>
2025-05-06 10:05 - DEBUG: Deactivating the card 5♥
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: Card clicked: 2♠
2025-05-06 10:05 - DEBUG: Activating the card: 2♠
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: <card.Card object at 0x755779bded00>
2025-05-06 10:05 - DEBUG: Deactivating the card 2♠
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:05 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: Card clicked: 3♥
2025-05-06 10:06 - DEBUG: Activating the card: 3♥
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: <card.Card object at 0x755779a94410>
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:06 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:10 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: None
2025-05-06 10:15 - DEBUG: Card clicked: 9♣
2025-05-06 10:15 - DEBUG: Activating the card: 9♣
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    if stock_pile.is_clicked():
       ~~~~~~~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    if stock_pile.is_clicked():
       ~~~~~~~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:15 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:16 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:16 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:16 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:16 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:16 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:16 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:16 - DEBUG: <card.Card object at 0x7df9ae36da50>
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: Card clicked: 3♠
2025-05-06 10:17 - DEBUG: Activating the card: 3♠
2025-05-06 10:17 - DEBUG: <card.Card object at 0x75fff7e38e90>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x75fff7e38e90>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x75fff7e38e90>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x75fff7e38e90>
2025-05-06 10:17 - ERROR: 'StockPile' object has no attribute 'width'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    if stock_pile.is_clicked(mouse_x, mouse_y):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 25, in is_clicked
    return self.x <= x < (self.x + self.width) and self.y <= y < (
                                   ^^^^^^^^^^
AttributeError: 'StockPile' object has no attribute 'width'
2025-05-06 10:17 - DEBUG: <card.Card object at 0x75fff7e38e90>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x75fff7e38e90>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x75fff7e38e90>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x75fff7e38e90>
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: None
2025-05-06 10:17 - DEBUG: Card clicked: 4♥
2025-05-06 10:17 - DEBUG: Activating the card: 4♥
2025-05-06 10:17 - DEBUG: <card.Card object at 0x78635c85df30>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x78635c85df30>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x78635c85df30>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x78635c85df30>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x78635c85df30>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x78635c85df30>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x78635c85df30>
2025-05-06 10:17 - DEBUG: <card.Card object at 0x78635c85df30>
2025-05-06 10:17 - ERROR: expect bytes or str, got int
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 164, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 150, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expect bytes or str, got int
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: Card clicked: 4♣
2025-05-06 10:18 - DEBUG: Activating the card: 4♣
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9d150>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9d150>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9d150>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9d150>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9d150>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9d150>
2025-05-06 10:18 - DEBUG: Deactivating the card 4♣
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: Card clicked: 7♠
2025-05-06 10:18 - DEBUG: Activating the card: 7♠
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e83750>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e83750>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e83750>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e83750>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e83750>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e83750>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e83750>
2025-05-06 10:18 - DEBUG: Deactivating the card 7♠
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: None
2025-05-06 10:18 - DEBUG: Card clicked: 10♣
2025-05-06 10:18 - DEBUG: Activating the card: 10♣
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - ERROR: Card.draw() missing 3 required positional arguments: 'x', 'y', and 'is_stockpile'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 164, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 152, in check_card
    card.draw()
    ~~~~~~~~~^^
TypeError: Card.draw() missing 3 required positional arguments: 'x', 'y', and 'is_stockpile'
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:18 - DEBUG: <card.Card object at 0x7d42c4e9ce50>
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: Card clicked: A♠
2025-05-06 10:21 - DEBUG: Activating the card: A♠
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d52302a430>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d52302a430>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d52302a430>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d52302a430>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d52302a430>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d52302a430>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d52302a430>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d52302a430>
2025-05-06 10:21 - DEBUG: Deactivating the card A♠
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: None
2025-05-06 10:21 - DEBUG: Card clicked: Q♣
2025-05-06 10:21 - DEBUG: Activating the card: Q♣
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:21 - DEBUG: <card.Card object at 0x74d522ea12d0>
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:49 - DEBUG: None
2025-05-06 10:50 - DEBUG: Card clicked: 5♣
2025-05-06 10:50 - DEBUG: Activating the card: 5♣
2025-05-06 10:50 - DEBUG: checkpoint 1
2025-05-06 10:50 - DEBUG: checkpoint 1
2025-05-06 10:50 - DEBUG: checkpoint 1
2025-05-06 10:50 - DEBUG: checkpoint 1
2025-05-06 10:50 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 164, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 150, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 10:50 - DEBUG: checkpoint 1
2025-05-06 10:50 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 164, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 150, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 10:52 - DEBUG: Card clicked: K♦
2025-05-06 10:52 - DEBUG: Activating the card: K♦
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 164, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 164, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 164, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 164, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 164, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 10:52 - DEBUG: checkpoint 1
2025-05-06 10:52 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 164, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 10:56 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 155, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 10:56 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 155, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 10:56 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 155, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 10:56 - DEBUG: Card clicked: 2♥
2025-05-06 10:56 - DEBUG: Activating the card: 2♥
2025-05-06 10:56 - DEBUG: Card clicked: K♥
2025-05-06 10:56 - DEBUG: Activating the card: K♥
2025-05-06 10:56 - DEBUG: Card clicked: Q♣
2025-05-06 10:56 - DEBUG: Activating the card: Q♣
2025-05-06 10:56 - DEBUG: Card clicked: 6♠
2025-05-06 10:56 - DEBUG: Activating the card: 6♠
2025-05-06 10:56 - DEBUG: Card clicked: 4♠
2025-05-06 10:56 - DEBUG: Activating the card: 4♠
2025-05-06 10:56 - DEBUG: Card clicked: 10♦
2025-05-06 10:56 - DEBUG: Activating the card: 10♦
2025-05-06 10:56 - DEBUG: Card clicked: 8♠
2025-05-06 10:56 - DEBUG: Activating the card: 8♠
2025-05-06 10:56 - DEBUG: Card clicked: K♠
2025-05-06 10:56 - DEBUG: Activating the card: K♠
2025-05-06 10:56 - DEBUG: Card clicked: 9♥
2025-05-06 10:56 - DEBUG: Activating the card: 9♥
2025-05-06 10:56 - DEBUG: Card clicked: 2♦
2025-05-06 10:56 - DEBUG: Activating the card: 2♦
2025-05-06 10:56 - DEBUG: Card clicked: 2♠
2025-05-06 10:56 - DEBUG: Activating the card: 2♠
2025-05-06 10:56 - DEBUG: Card clicked: 5♦
2025-05-06 10:56 - DEBUG: Activating the card: 5♦
2025-05-06 10:56 - DEBUG: Card clicked: 9♦
2025-05-06 10:56 - DEBUG: Activating the card: 9♦
2025-05-06 10:56 - DEBUG: Card clicked: 7♣
2025-05-06 10:56 - DEBUG: Activating the card: 7♣
2025-05-06 10:56 - DEBUG: Card clicked: K♦
2025-05-06 10:56 - DEBUG: Activating the card: K♦
2025-05-06 10:56 - DEBUG: Card clicked: A♥
2025-05-06 10:56 - DEBUG: Activating the card: A♥
2025-05-06 10:56 - DEBUG: Card clicked: 8♥
2025-05-06 10:56 - DEBUG: Activating the card: 8♥
2025-05-06 10:56 - DEBUG: Card clicked: 4♥
2025-05-06 10:56 - DEBUG: Activating the card: 4♥
2025-05-06 10:56 - DEBUG: Card clicked: J♣
2025-05-06 10:56 - DEBUG: Activating the card: J♣
2025-05-06 10:56 - DEBUG: Card clicked: 3♠
2025-05-06 10:56 - DEBUG: Activating the card: 3♠
2025-05-06 10:56 - DEBUG: Card clicked: 3♦
2025-05-06 10:56 - DEBUG: Activating the card: 3♦
2025-05-06 10:56 - DEBUG: Card clicked: Q♥
2025-05-06 10:56 - DEBUG: Activating the card: Q♥
2025-05-06 10:56 - DEBUG: Card clicked: A♣
2025-05-06 10:56 - DEBUG: Activating the card: A♣
2025-05-06 10:56 - DEBUG: Card clicked: 5♣
2025-05-06 10:56 - DEBUG: Activating the card: 5♣
2025-05-06 10:56 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 155, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 10:56 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 155, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 10:56 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 155, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 10:56 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 155, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 10:56 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 163, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 155, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 10:56 - DEBUG: Deactivating the card 2♥
2025-05-06 10:56 - DEBUG: Deactivating the card K♥
2025-05-06 10:56 - DEBUG: Deactivating the card Q♣
2025-05-06 10:56 - DEBUG: Deactivating the card 6♠
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - DEBUG: Card clicked: 8♥
2025-05-06 14:29 - DEBUG: Activating the card: 8♥
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 128, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:29 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 14:29 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 14:30 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 14:30 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 14:30 - DEBUG: Deactivating the card 8♥
2025-05-06 14:30 - DEBUG: Card clicked: 4♥
2025-05-06 14:30 - DEBUG: Activating the card: 4♥
2025-05-06 14:30 - DEBUG: Card clicked: K♠
2025-05-06 14:30 - DEBUG: Activating the card: K♠
2025-05-06 14:30 - DEBUG: Card clicked: A♠
2025-05-06 14:30 - DEBUG: Activating the card: A♠
2025-05-06 14:30 - DEBUG: Card clicked: 6♦
2025-05-06 14:30 - DEBUG: Activating the card: 6♦
2025-05-06 14:30 - DEBUG: Card clicked: 9♠
2025-05-06 14:30 - DEBUG: Activating the card: 9♠
2025-05-06 14:30 - DEBUG: Card clicked: Q♠
2025-05-06 14:30 - DEBUG: Activating the card: Q♠
2025-05-06 14:30 - DEBUG: Card clicked: Q♥
2025-05-06 14:30 - DEBUG: Activating the card: Q♥
2025-05-06 14:30 - DEBUG: Card clicked: 8♦
2025-05-06 14:30 - DEBUG: Activating the card: 8♦
2025-05-06 14:30 - DEBUG: Card clicked: 6♠
2025-05-06 14:30 - DEBUG: Activating the card: 6♠
2025-05-06 14:30 - DEBUG: Card clicked: Q♦
2025-05-06 14:30 - DEBUG: Activating the card: Q♦
2025-05-06 14:30 - DEBUG: Card clicked: K♣
2025-05-06 14:30 - DEBUG: Activating the card: K♣
2025-05-06 14:30 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 14:30 - DEBUG: Deactivating the card 4♥
2025-05-06 14:30 - DEBUG: Deactivating the card K♠
2025-05-06 14:30 - DEBUG: Deactivating the card A♠
2025-05-06 14:30 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 159, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 151, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 14:58 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:58 - DEBUG: Activating the card: 7♠
2025-05-06 14:58 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:58 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:58 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:58 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:58 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:58 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:58 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:58 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:59 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:59 - DEBUG: Activating the card: 4♥
2025-05-06 14:59 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:59 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:59 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 160, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 129, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 14:59 - DEBUG: Activating the card: A♠
2025-05-06 14:59 - DEBUG: Deactivating the card A♠
2025-05-06 14:59 - DEBUG: Activating the card: A♥
2025-05-06 14:59 - DEBUG: Deactivating the card A♥
2025-05-06 14:59 - DEBUG: Activating the card: 7♥
2025-05-06 15:01 - DEBUG: Activating the card: A♣
2025-05-06 15:01 - DEBUG: Deactivating the card A♣
2025-05-06 15:02 - DEBUG: Activating the card: 9♠
2025-05-06 15:02 - DEBUG: Deactivating the card 9♠
2025-05-06 15:02 - DEBUG: Activating the card: A♠
2025-05-06 15:02 - DEBUG: Deactivating the card A♠
2025-05-06 15:02 - DEBUG: Activating the card: A♠
2025-05-06 15:02 - DEBUG: Deactivating the card A♠
2025-05-06 15:02 - DEBUG: Activating the card: A♠
2025-05-06 15:02 - DEBUG: Deactivating the card A♠
2025-05-06 15:02 - DEBUG: Activating the card: 4♦
2025-05-06 15:02 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 130, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 15:02 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 130, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 15:02 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 130, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 15:02 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 130, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 15:02 - ERROR: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    turned_card.undraw()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 130, in undraw
    self.window.addstr(self.x, y, " ", self.width)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-06 15:04 - DEBUG: Activating the card: J♣
2025-05-06 15:04 - DEBUG: Deactivating the card J♣
2025-05-06 15:05 - DEBUG: Activating the card: A♦
2025-05-06 15:05 - DEBUG: Deactivating the card A♦
2025-05-06 15:05 - DEBUG: Activating the card: J♣
2025-05-06 15:05 - DEBUG: Deactivating the card J♣
2025-05-06 15:05 - DEBUG: Activating the card: Q♠
2025-05-06 15:05 - DEBUG: Deactivating the card Q♠
2025-05-06 15:05 - DEBUG: Activating the card: 7♠
2025-05-06 15:05 - DEBUG: Deactivating the card 7♠
2025-05-06 15:05 - DEBUG: Activating the card: 8♠
2025-05-06 15:05 - DEBUG: Deactivating the card 8♠
2025-05-06 15:05 - DEBUG: Activating the card: 9♠
2025-05-06 15:05 - DEBUG: Deactivating the card 9♠
2025-05-06 15:05 - DEBUG: Activating the card: 9♠
2025-05-06 15:05 - DEBUG: Deactivating the card 9♠
2025-05-06 15:05 - DEBUG: Activating the card: 8♠
2025-05-06 15:05 - DEBUG: Deactivating the card 8♠
2025-05-06 15:05 - DEBUG: Activating the card: 9♠
2025-05-06 15:05 - DEBUG: Deactivating the card 9♠
2025-05-06 15:05 - DEBUG: Activating the card: 8♠
2025-05-06 15:05 - DEBUG: Deactivating the card 8♠
2025-05-06 15:05 - DEBUG: Activating the card: 8♠
2025-05-06 15:05 - DEBUG: Deactivating the card 8♠
2025-05-06 15:10 - ERROR: An error occurred: 'TableauPile' object has no attribute 'add_card'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/main.py", line 49, in <module>
    curses.wrapper(main)
    ~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/franek/gigathon2025/gigathon2025-solitaire/main.py", line 37, in main
    game(window)
    ~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 72, in game
    lasted_cards, tableau_piles = Tableau(cards).draw()
                                  ~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 119, in draw
    current_pile.add_card(card)  # Add to current pile
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TableauPile' object has no attribute 'add_card'
2025-05-06 15:11 - DEBUG: Activating the card: J♣
2025-05-06 15:11 - DEBUG: Activating the card: 9♠
2025-05-06 15:11 - DEBUG: Activating the card: 10♦
2025-05-06 15:11 - DEBUG: Activating the card: 6♣
2025-05-06 15:11 - DEBUG: Activating the card: J♦
2025-05-06 15:11 - DEBUG: Activating the card: 10♣
2025-05-06 15:11 - DEBUG: Activating the card: J♠
2025-05-06 15:11 - DEBUG: Activating the card: 9♣
2025-05-06 15:11 - DEBUG: Activating the card: J♥
2025-05-06 15:11 - DEBUG: Activating the card: K♥
2025-05-06 15:11 - DEBUG: Activating the card: 10♥
2025-05-06 15:11 - DEBUG: Activating the card: A♣
2025-05-06 15:15 - DEBUG: Activating the card: A♥
2025-05-06 15:15 - DEBUG: Deactivating the card A♥
2025-05-06 15:16 - DEBUG: Activating the card: 5♥
2025-05-06 15:16 - DEBUG: Activating the card: 6♥
2025-05-06 15:16 - DEBUG: Activating the card: Q♥
2025-05-06 15:16 - DEBUG: Activating the card: J♥
2025-05-06 15:16 - DEBUG: Activating the card: 6♠
2025-05-06 15:16 - DEBUG: Activating the card: J♠
2025-05-06 15:16 - DEBUG: Activating the card: 9♠
2025-05-06 15:16 - DEBUG: Activating the card: 7♥
2025-05-06 15:16 - DEBUG: Activating the card: 4♠
2025-05-06 15:16 - DEBUG: Activating the card: 3♣
2025-05-06 15:16 - DEBUG: Activating the card: Q♦
2025-05-06 15:16 - DEBUG: Activating the card: 4♣
2025-05-06 15:16 - DEBUG: Activating the card: 8♥
2025-05-06 15:16 - DEBUG: Deactivating the card 6♥
2025-05-06 15:16 - DEBUG: Deactivating the card Q♥
2025-05-06 15:16 - DEBUG: Deactivating the card J♥
2025-05-06 15:16 - DEBUG: Deactivating the card 6♠
2025-05-06 15:16 - DEBUG: Deactivating the card J♠
2025-05-06 15:17 - DEBUG: Deactivating the card 9♠
2025-05-06 15:17 - DEBUG: Deactivating the card 7♥
2025-05-06 15:17 - DEBUG: Deactivating the card 4♠
2025-05-06 15:17 - DEBUG: Deactivating the card 3♣
2025-05-06 15:18 - DEBUG: Activating the card: J♣
2025-05-06 15:18 - DEBUG: Activating the card: 7♥
2025-05-06 15:18 - DEBUG: Activating the card: 6♠
2025-05-06 15:18 - DEBUG: Activating the card: Q♦
2025-05-06 15:18 - DEBUG: Activating the card: 10♦
2025-05-06 15:18 - DEBUG: Activating the card: 4♦
2025-05-06 15:18 - DEBUG: Activating the card: 7♣
2025-05-06 15:18 - DEBUG: Activating the card: 6♦
2025-05-06 15:18 - DEBUG: Activating the card: K♥
2025-05-06 15:18 - DEBUG: Activating the card: 2♦
2025-05-06 15:18 - DEBUG: Activating the card: 10♣
2025-05-06 15:18 - DEBUG: Activating the card: 3♦
2025-05-06 15:18 - DEBUG: Activating the card: 8♥
2025-05-06 15:18 - DEBUG: Activating the card: 10♥
2025-05-06 15:18 - DEBUG: Activating the card: 9♠
2025-05-06 15:18 - DEBUG: Activating the card: A♣
2025-05-06 15:18 - DEBUG: Activating the card: A♥
2025-05-06 15:19 - ERROR: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 154, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 132, in undraw
    self.window.addstr(" " * self.width+1)
                       ~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "int") to str
2025-05-06 15:19 - DEBUG: Activating the card: 10♥
2025-05-06 15:19 - ERROR: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 154, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 132, in undraw
    self.window.addstr(" " * self.width+1)
                       ~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "int") to str
2025-05-06 15:19 - ERROR: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 154, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 132, in undraw
    self.window.addstr(" " * self.width+1)
                       ~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "int") to str
2025-05-06 15:19 - ERROR: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 154, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 132, in undraw
    self.window.addstr(" " * self.width+1)
                       ~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "int") to str
2025-05-06 15:19 - DEBUG: Deactivating the card 10♥
2025-05-06 15:19 - DEBUG: Activating the card: 5♣
2025-05-06 15:19 - DEBUG: Activating the card: J♠
2025-05-06 15:19 - DEBUG: Activating the card: 9♣
2025-05-06 15:19 - ERROR: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 154, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 132, in undraw
    self.window.addstr(" " * self.width+1)
                       ~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "int") to str
2025-05-06 15:19 - DEBUG: Deactivating the card 5♣
2025-05-06 15:19 - DEBUG: Deactivating the card J♠
2025-05-06 15:19 - DEBUG: Deactivating the card 9♣
2025-05-06 15:21 - ERROR: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 158, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 132, in undraw
    self.window.addstr(" " * self.width+1)
                       ~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "int") to str
2025-05-06 15:21 - DEBUG: Activating the card: A♦
2025-05-06 15:21 - ERROR: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 158, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 132, in undraw
    self.window.addstr(" " * self.width+1)
                       ~~~~~~~~~~~~~~~~^~
TypeError: can only concatenate str (not "int") to str
2025-05-06 15:21 - DEBUG: Deactivating the card A♦
2025-05-06 15:22 - ERROR: can't multiply sequence by non-int of type 'str'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 158, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 132, in undraw
    self.window.addstr(" " * str(self.width+1))
                       ~~~~^~~~~~~~~~~~~~~~~~~
TypeError: can't multiply sequence by non-int of type 'str'
2025-05-06 15:22 - DEBUG: Activating the card: Q♣
2025-05-06 15:22 - ERROR: can't multiply sequence by non-int of type 'str'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 158, in check_card
    card.undraw()
    ~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/card.py", line 132, in undraw
    self.window.addstr(" " * str(self.width+1))
                       ~~~~^~~~~~~~~~~~~~~~~~~
TypeError: can't multiply sequence by non-int of type 'str'
2025-05-06 15:22 - DEBUG: Deactivating the card Q♣
2025-05-06 16:15 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 166, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-06 16:16 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 147, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 16:16 - DEBUG: Activating the card: 7♥
2025-05-06 16:16 - DEBUG: Activating the card: 5♠
2025-05-06 16:16 - DEBUG: Activating the card: A♠
2025-05-06 16:16 - DEBUG: Activating the card: Q♦
2025-05-06 16:16 - DEBUG: Activating the card: 2♦
2025-05-06 16:16 - DEBUG: Activating the card: 9♠
2025-05-06 16:16 - DEBUG: Activating the card: 2♥
2025-05-06 16:16 - DEBUG: Activating the card: K♦
2025-05-06 16:16 - DEBUG: Activating the card: 2♣
2025-05-06 16:16 - DEBUG: Activating the card: 6♥
2025-05-06 16:16 - DEBUG: Activating the card: A♥
2025-05-06 16:16 - DEBUG: Activating the card: 9♥
2025-05-06 16:16 - DEBUG: Activating the card: 2♠
2025-05-06 16:16 - DEBUG: Activating the card: J♦
2025-05-06 16:16 - DEBUG: Activating the card: 8♦
2025-05-06 16:16 - DEBUG: Activating the card: 3♥
2025-05-06 16:16 - DEBUG: Activating the card: 6♠
2025-05-06 16:16 - DEBUG: Activating the card: 10♠
2025-05-06 16:16 - DEBUG: Activating the card: 10♥
2025-05-06 16:16 - DEBUG: Activating the card: 10♦
2025-05-06 16:16 - DEBUG: Activating the card: 3♦
2025-05-06 16:16 - DEBUG: Activating the card: 6♣
2025-05-06 16:16 - DEBUG: Activating the card: A♣
2025-05-06 16:16 - DEBUG: Activating the card: J♥
2025-05-06 16:16 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 147, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 16:16 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 147, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 16:16 - DEBUG: Deactivating the card 7♥
2025-05-06 16:16 - DEBUG: Deactivating the card 5♠
2025-05-06 16:16 - DEBUG: Deactivating the card A♠
2025-05-06 16:16 - DEBUG: Deactivating the card Q♦
2025-05-06 16:16 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 147, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-06 16:29 - ERROR: StockPile.check_card() missing 1 required positional argument: 'window'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
TypeError: StockPile.check_card() missing 1 required positional argument: 'window'
2025-05-06 16:29 - ERROR: StockPile.check_card() missing 1 required positional argument: 'window'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
TypeError: StockPile.check_card() missing 1 required positional argument: 'window'
2025-05-06 16:29 - ERROR: StockPile.check_card() missing 1 required positional argument: 'window'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
TypeError: StockPile.check_card() missing 1 required positional argument: 'window'
2025-05-06 16:29 - ERROR: StockPile.check_card() missing 1 required positional argument: 'window'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
TypeError: StockPile.check_card() missing 1 required positional argument: 'window'
2025-05-06 16:29 - ERROR: StockPile.check_card() missing 1 required positional argument: 'window'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card()
    ~~~~~~~~~~~~~~~~~~~~~^^
TypeError: StockPile.check_card() missing 1 required positional argument: 'window'
2025-05-07 08:26 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 182, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-07 08:26 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-07 08:26 - DEBUG: Activating the card: A♠
2025-05-07 08:26 - DEBUG: Activating the card: K♣
2025-05-07 08:26 - DEBUG: Activating the card: 5♣
2025-05-07 08:26 - DEBUG: Activating the card: 3♥
2025-05-07 08:26 - DEBUG: Activating the card: Q♥
2025-05-07 08:26 - DEBUG: Activating the card: A♥
2025-05-07 08:26 - DEBUG: Activating the card: 2♦
2025-05-07 08:26 - DEBUG: Activating the card: 3♦
2025-05-07 08:26 - DEBUG: Activating the card: 5♠
2025-05-07 08:26 - DEBUG: Activating the card: 9♥
2025-05-07 08:26 - DEBUG: Activating the card: 3♠
2025-05-07 08:26 - DEBUG: Activating the card: 2♠
2025-05-07 08:26 - DEBUG: Activating the card: 6♥
2025-05-07 08:26 - DEBUG: Activating the card: 2♥
2025-05-07 08:26 - DEBUG: Activating the card: A♦
2025-05-07 08:26 - DEBUG: Activating the card: A♣
2025-05-07 08:26 - DEBUG: Activating the card: 4♦
2025-05-07 08:26 - DEBUG: Activating the card: K♥
2025-05-07 08:26 - DEBUG: Activating the card: 8♠
2025-05-07 08:26 - DEBUG: Activating the card: J♦
2025-05-07 08:26 - DEBUG: Activating the card: K♦
2025-05-07 08:26 - DEBUG: Activating the card: J♣
2025-05-07 08:26 - DEBUG: Activating the card: 5♦
2025-05-07 08:26 - DEBUG: Activating the card: 4♣
2025-05-07 08:26 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-07 08:26 - DEBUG: Deactivating the card A♠
2025-05-07 08:26 - DEBUG: Deactivating the card K♣
2025-05-07 08:26 - DEBUG: Deactivating the card 5♣
2025-05-07 08:26 - DEBUG: Deactivating the card 3♥
2025-05-07 08:27 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 182, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-07 08:27 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-07 08:27 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-07 08:27 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-07 08:27 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 161, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-07 08:27 - DEBUG: Activating the card: 4♦
2025-05-07 08:27 - DEBUG: Activating the card: 3♠
2025-05-07 08:27 - DEBUG: Activating the card: 3♦
2025-05-07 08:27 - DEBUG: Activating the card: K♠
2025-05-07 08:27 - DEBUG: Activating the card: 3♥
2025-05-07 08:27 - DEBUG: Activating the card: 10♠
2025-05-07 08:27 - DEBUG: Activating the card: 10♦
2025-05-07 08:27 - DEBUG: Activating the card: A♥
2025-05-07 08:27 - DEBUG: Activating the card: 4♠
2025-05-07 08:27 - DEBUG: Activating the card: J♠
2025-05-07 08:27 - DEBUG: Activating the card: 2♦
2025-05-07 08:27 - DEBUG: Activating the card: 7♥
2025-05-07 08:27 - DEBUG: Activating the card: 2♠
2025-05-07 08:27 - DEBUG: Activating the card: 6♠
2025-05-07 08:27 - DEBUG: Activating the card: 10♥
2025-05-07 08:27 - DEBUG: Activating the card: J♣
2025-05-07 08:27 - DEBUG: Activating the card: K♦
2025-05-07 08:27 - DEBUG: Activating the card: 4♣
2025-05-07 08:27 - DEBUG: Activating the card: Q♦
2025-05-07 08:27 - DEBUG: Activating the card: 6♣
2025-05-07 08:27 - DEBUG: Activating the card: 7♣
2025-05-07 08:27 - DEBUG: Activating the card: 9♣
2025-05-07 08:27 - DEBUG: Activating the card: 2♥
2025-05-07 08:27 - DEBUG: Activating the card: 8♣
2025-05-07 08:27 - DEBUG: Deactivating the card 4♦
2025-05-07 08:27 - DEBUG: Deactivating the card 3♠
2025-05-07 08:27 - DEBUG: Deactivating the card 3♦
2025-05-07 08:27 - DEBUG: Deactivating the card K♠
2025-05-07 08:39 - DEBUG: Activating the card: 4♣
2025-05-07 08:39 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 77, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 08:39 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 77, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 08:40 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 77, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 08:40 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 185, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-07 08:40 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 164, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-07 08:40 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 158, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 164, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-07 08:40 - DEBUG: Activating the card: 2♦
2025-05-07 08:40 - DEBUG: Activating the card: 5♣
2025-05-07 08:40 - DEBUG: Activating the card: A♦
2025-05-07 08:40 - DEBUG: Activating the card: 9♣
2025-05-07 08:40 - DEBUG: Activating the card: 2♥
2025-05-07 08:40 - DEBUG: Activating the card: 9♦
2025-05-07 08:40 - DEBUG: Activating the card: 6♥
2025-05-07 08:40 - DEBUG: Activating the card: K♣
2025-05-07 08:40 - DEBUG: Activating the card: 5♠
2025-05-07 08:40 - DEBUG: Activating the card: 8♠
2025-05-07 08:40 - DEBUG: Activating the card: K♦
2025-05-07 08:40 - DEBUG: Activating the card: 7♣
2025-05-07 08:40 - DEBUG: Activating the card: 8♥
2025-05-07 08:40 - DEBUG: Activating the card: 6♦
2025-05-07 08:40 - DEBUG: Activating the card: 4♣
2025-05-07 08:40 - DEBUG: Activating the card: Q♦
2025-05-07 08:40 - DEBUG: Activating the card: 9♠
2025-05-07 08:40 - DEBUG: Activating the card: 10♠
2025-05-07 08:40 - DEBUG: Activating the card: 3♠
2025-05-07 08:40 - DEBUG: Activating the card: 5♥
2025-05-07 08:40 - DEBUG: Activating the card: 3♥
2025-05-07 08:40 - DEBUG: Activating the card: A♥
2025-05-07 08:40 - DEBUG: Activating the card: 10♣
2025-05-07 08:40 - DEBUG: Activating the card: 7♦
2025-05-07 08:40 - DEBUG: Activating the card: A♣
2025-05-07 08:40 - DEBUG: Activating the card: J♠
2025-05-07 08:40 - DEBUG: Activating the card: 9♦
2025-05-07 08:40 - DEBUG: Activating the card: K♣
2025-05-07 08:40 - DEBUG: Deactivating the card A♣
2025-05-07 08:40 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 77, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 08:48 - ERROR: An error occurred: 'float' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/main.py", line 49, in <module>
    curses.wrapper(main)
    ~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/franek/gigathon2025/gigathon2025-solitaire/main.py", line 37, in main
    game(window)
    ~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 79, in game
    foundation_hearts.draw()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 74, in draw
    self.window.addstr(self.x + self.width/2 -1, self.y + self.height - 1, suit_symbol)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer
2025-05-07 08:49 - ERROR: An error occurred: addwstr() returned ERR
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/main.py", line 49, in <module>
    curses.wrapper(main)
    ~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/franek/gigathon2025/gigathon2025-solitaire/main.py", line 37, in main
    game(window)
    ~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 79, in game
    foundation_hearts.draw()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 74, in draw
    self.window.addstr(int(self.x + self.width/2 -1), int(self.y + self.height - 1), suit_symbol)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_curses.error: addwstr() returned ERR
2025-05-07 08:53 - DEBUG: Activating the card: A♥
2025-05-07 08:53 - DEBUG: Activating the card: 2♣
2025-05-07 08:53 - DEBUG: Activating the card: 5♥
2025-05-07 08:53 - DEBUG: Deactivating the card A♥
2025-05-07 08:53 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 88, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 08:53 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 88, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 08:53 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 88, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 08:54 - DEBUG: Activating the card: 2♣
2025-05-07 08:54 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 88, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 08:54 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 88, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 08:54 - DEBUG: Activating the card: A♥
2025-05-07 08:54 - DEBUG: Deactivating the card A♥
2025-05-07 09:28 - DEBUG: Activating the card: A♣
2025-05-07 09:28 - DEBUG: Deactivating the card A♣
2025-05-07 09:28 - DEBUG: Activating the card: A♦
2025-05-07 09:28 - DEBUG: Activating the card: 5♦
2025-05-07 09:28 - DEBUG: Activating the card: 5♠
2025-05-07 09:28 - DEBUG: Activating the card: J♥
2025-05-07 09:28 - DEBUG: Deactivating the card A♦
2025-05-07 09:29 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 87, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 09:29 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 87, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 09:29 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 87, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-07 09:29 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 149, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 87, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-08 07:36 - DEBUG: Activating the card: A♥
2025-05-08 07:36 - DEBUG: Deactivating the card A♥
2025-05-08 07:36 - DEBUG: Activating the card: 2♥
2025-05-08 07:36 - DEBUG: Activating the card: 9♠
2025-05-08 07:36 - DEBUG: Activating the card: A♣
2025-05-08 07:36 - DEBUG: Activating the card: 3♠
2025-05-08 07:36 - DEBUG: Activating the card: 7♦
2025-05-08 07:36 - DEBUG: Activating the card: K♥
2025-05-08 07:36 - DEBUG: Activating the card: 4♥
2025-05-08 07:36 - DEBUG: Activating the card: 10♦
2025-05-08 07:36 - DEBUG: Activating the card: 5♥
2025-05-08 07:36 - DEBUG: Activating the card: 6♥
2025-05-08 07:36 - DEBUG: Activating the card: 10♣
2025-05-08 07:36 - DEBUG: Activating the card: Q♥
2025-05-08 07:36 - DEBUG: Activating the card: Q♠
2025-05-08 07:36 - DEBUG: Activating the card: 2♠
2025-05-08 07:36 - DEBUG: Activating the card: 8♥
2025-05-08 07:36 - DEBUG: Activating the card: 10♠
2025-05-08 07:36 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 152, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 88, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-08 07:36 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 152, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 88, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-08 07:36 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 152, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 88, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-08 07:36 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 152, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 88, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-08 07:36 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 152, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 88, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-08 07:45 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 07:45 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 171, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-08 07:45 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 171, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-08 07:45 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 171, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-08 07:45 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 171, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-08 07:45 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 171, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-08 07:45 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 171, in check_card
    card = self.card_list[-1]
           ~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-05-08 07:57 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 169, in check_card
    if self.is_clicked():
       ~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-08 07:57 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 169, in check_card
    if self.is_clicked():
       ~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-08 07:57 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 169, in check_card
    if self.is_clicked():
       ~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-08 07:57 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 169, in check_card
    if self.is_clicked():
       ~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-08 07:57 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 169, in check_card
    if self.is_clicked():
       ~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-08 07:57 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 169, in check_card
    if self.is_clicked():
       ~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-08 07:57 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 169, in check_card
    if self.is_clicked():
       ~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-08 07:57 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 169, in check_card
    if self.is_clicked():
       ~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-08 07:57 - ERROR: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 168, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 169, in check_card
    if self.is_clicked():
       ~~~~~~~~~~~~~~~^^
TypeError: Pile.is_clicked() missing 2 required positional arguments: 'x' and 'y'
2025-05-08 07:58 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 07:58 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 07:58 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 07:58 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 07:58 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 07:58 - DEBUG: Activating the card: K♥
2025-05-08 07:58 - DEBUG: Activating the card: 6♥
2025-05-08 07:58 - DEBUG: Activating the card: 10♦
2025-05-08 07:58 - DEBUG: Activating the card: A♥
2025-05-08 07:58 - DEBUG: Activating the card: 5♥
2025-05-08 07:58 - DEBUG: Activating the card: J♦
2025-05-08 07:58 - DEBUG: Activating the card: 8♥
2025-05-08 07:58 - DEBUG: Activating the card: 2♦
2025-05-08 07:58 - DEBUG: Activating the card: 5♣
2025-05-08 07:58 - DEBUG: Activating the card: 8♣
2025-05-08 07:58 - DEBUG: Activating the card: 10♠
2025-05-08 07:58 - DEBUG: Activating the card: 9♥
2025-05-08 07:58 - DEBUG: Activating the card: A♣
2025-05-08 07:58 - DEBUG: Activating the card: 10♣
2025-05-08 07:58 - DEBUG: Activating the card: 2♠
2025-05-08 07:58 - DEBUG: Activating the card: Q♠
2025-05-08 07:58 - DEBUG: Activating the card: 7♦
2025-05-08 07:58 - DEBUG: Activating the card: 3♣
2025-05-08 07:58 - DEBUG: Activating the card: J♠
2025-05-08 07:58 - DEBUG: Activating the card: 6♣
2025-05-08 07:58 - DEBUG: Activating the card: A♠
2025-05-08 07:58 - DEBUG: Activating the card: 4♥
2025-05-08 07:58 - DEBUG: Activating the card: 4♠
2025-05-08 07:58 - DEBUG: Activating the card: K♦
2025-05-08 07:58 - ERROR: list index out of range
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 152, in game
    pile.maybe_move(
    ~~~~~~~~~~~~~~~^
        active_card
        ^^^^^^^^^^^
    )  # Move the card if it's possible
    ^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 86, in maybe_move
    if self.num == self.card_list[self.num].num.value + 1:
                   ~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
2025-05-08 08:08 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 08:08 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 08:08 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 08:08 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 08:08 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 192, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-08 08:08 - DEBUG: Activating the card: 7♣
2025-05-08 08:08 - DEBUG: Activating the card: 10♦
2025-05-08 08:08 - DEBUG: Activating the card: 2♠
2025-05-08 08:08 - DEBUG: Activating the card: 10♠
2025-05-08 08:08 - DEBUG: Activating the card: 6♥
2025-05-08 08:08 - DEBUG: Activating the card: J♠
2025-05-08 08:08 - DEBUG: Activating the card: 8♦
2025-05-08 08:08 - DEBUG: Activating the card: 10♥
2025-05-08 08:08 - DEBUG: Activating the card: 4♠
2025-05-08 08:08 - DEBUG: Activating the card: 2♥
2025-05-08 08:08 - DEBUG: Activating the card: 4♥
2025-05-08 08:08 - DEBUG: Activating the card: 7♠
2025-05-08 08:08 - DEBUG: Activating the card: Q♠
2025-05-08 08:08 - DEBUG: Activating the card: J♦
2025-05-08 08:08 - DEBUG: Activating the card: 7♥
2025-05-08 08:08 - DEBUG: Activating the card: 8♠
2025-05-08 08:08 - DEBUG: Activating the card: K♦
2025-05-08 08:08 - DEBUG: Activating the card: Q♥
2025-05-08 08:08 - DEBUG: Activating the card: Q♣
2025-05-08 08:08 - DEBUG: Activating the card: 6♦
2025-05-08 08:08 - DEBUG: Activating the card: 9♥
2025-05-08 08:08 - DEBUG: Activating the card: 2♣
2025-05-08 08:08 - DEBUG: Activating the card: 6♠
2025-05-08 08:08 - DEBUG: Activating the card: 8♣
2025-05-08 17:55 - ERROR: StockPile.check_card() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPile.check_card() takes 2 positional arguments but 4 were given
2025-05-08 17:55 - ERROR: StockPile.check_card() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPile.check_card() takes 2 positional arguments but 4 were given
2025-05-08 17:55 - ERROR: StockPile.check_card() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPile.check_card() takes 2 positional arguments but 4 were given
2025-05-08 17:55 - ERROR: StockPile.check_card() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPile.check_card() takes 2 positional arguments but 4 were given
2025-05-08 17:56 - ERROR: StockPile.check_card() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPile.check_card() takes 2 positional arguments but 4 were given
2025-05-08 17:56 - ERROR: StockPile.check_card() takes 2 positional arguments but 4 were given
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 167, in game
    stock_pile.check_card(stdscr, mouse_x, mouse_y)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StockPile.check_card() takes 2 positional arguments but 4 were given
2025-05-09 07:17 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 169, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 204, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-09 07:17 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 169, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 204, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
2025-05-09 07:17 - DEBUG: Activating the card: 7♣
2025-05-09 07:17 - DEBUG: Activating the card: 4♥
2025-05-09 07:17 - DEBUG: Activating the card: 5♣
2025-05-09 07:17 - DEBUG: Activating the card: 4♦
2025-05-09 07:17 - DEBUG: Activating the card: 9♠
2025-05-09 07:17 - DEBUG: Activating the card: 7♥
2025-05-09 07:17 - DEBUG: Activating the card: Q♦
2025-05-09 07:17 - DEBUG: Activating the card: 6♦
2025-05-09 07:17 - DEBUG: Activating the card: 5♥
2025-05-09 07:17 - DEBUG: Activating the card: 3♣
2025-05-09 07:17 - DEBUG: Activating the card: 7♦
2025-05-09 07:17 - DEBUG: Activating the card: K♦
2025-05-09 07:17 - DEBUG: Activating the card: 5♠
2025-05-09 07:17 - DEBUG: Activating the card: J♣
2025-05-09 07:17 - DEBUG: Activating the card: 10♦
2025-05-09 07:17 - DEBUG: Activating the card: 7♠
2025-05-09 07:17 - DEBUG: Activating the card: 4♠
2025-05-09 07:17 - DEBUG: Activating the card: 2♥
2025-05-09 07:17 - DEBUG: Activating the card: 3♥
2025-05-09 07:17 - DEBUG: Activating the card: 8♥
2025-05-09 07:17 - DEBUG: Activating the card: 9♦
2025-05-09 07:17 - DEBUG: Activating the card: 10♣
2025-05-09 07:17 - DEBUG: Activating the card: 8♣
2025-05-09 07:17 - DEBUG: Activating the card: 8♠
2025-05-09 07:17 - ERROR: cannot pickle '_curses.window' object
Traceback (most recent call last):
  File "/home/franek/gigathon2025/gigathon2025-solitaire/game.py", line 169, in game
    stock_pile.check_card(stdscr)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/franek/gigathon2025/gigathon2025-solitaire/piles.py", line 204, in check_card
    for card in copy.deepcopy(self.turned_card_list):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 197, in _deepcopy_list
    append(deepcopy(a, memo))
           ~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 163, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.13/copy.py", line 260, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.13/copy.py", line 137, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.13/copy.py", line 222, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_curses.window' object
